apiVersion: v1
kind: Secret
metadata:
  name: paybridge-api-gateway-secret
  namespace: paybridge
type: Opaque
stringData:
  JWT_SECRET: "a3f9c7e12b5d4f9083e2c1a7d9b8f6c4a1e0d3f2b4c59687e0b1c4d2f9a7b3c1"