apiVersion: v1
kind: Service
metadata:
  name: paybridge-postgres
  namespace: paybridge
spec:
  selector:
    app: paybridge-postgres
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP