apiVersion: v1
kind: ConfigMap
metadata:
  name: paybridge-user-svc-config
  namespace: paybridge
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://paybridge-postgres:5432/paybridge_user"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  TRANSACTION_SERVICE_ENDPOINT: "http://paybridge-transaction-svc:8082"
  JWT_TTL: "86400000"
  POSTGRES_DB: "paybridge_user"