apiVersion: apps/v1
kind: Deployment
metadata:
  name: paybridge-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paybridge-web
  template:
    metadata:
      labels:
        app: paybridge-web
    spec:
      containers:
        - name: web
          image: dentamuhajir/paybridge-web:1.0.0
          ports:
            - containerPort: 80
