apiVersion: apps/v1
kind: Deployment
metadata:
  name: paybridge-redis
  namespace: paybridge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paybridge-redis
  template:
    metadata:
      labels:
        app: paybridge-redis
    spec:
      containers:
        - name: redis
          image: redis:7
          ports:
            - containerPort: 6379
          command:
            - redis-server
            - "--requirepass"
            - "$(REDIS_PASSWORD)"
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: paybridge-redis-secret
                  key: REDIS_PASSWORD
          volumeMounts:
            - name: redis-storage
              mountPath: /data
      volumes:
        - name: redis-storage
          persistentVolumeClaim:
            claimName: paybridge-redis-pvc