apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: paybridge

resources:
  - namespaces/paybridge.yaml
  - infrastructures
  - applications

commonLabels:
  project: paybridge
  env: development