apiVersion: v1
kind: ConfigMap
metadata:
  name: paybridge-otel-collector-config
  namespace: paybridge
data:
  otel-collector-config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:

    processors:
      batch:

    exporters:
      otlp:
        endpoint: paybridge-jaeger:4317
        tls:
          insecure: true

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp]